import { useEffect, useMemo, useState } from "react";
import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { Building2, ExternalLink, LayoutDashboard, RefreshCw, Search, ShieldCheck, Store, Users } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { useCurrentUserState } from "@/lib/auth/use-current-user";
import { getAdminDashboard, LEAD_STATUSES, type AdminDashboard, type LeadStatus } from "@/lib/menu/admin";
import { getPlatformDashboard, updatePlatformTenantStatus, type PlatformDashboard, type PlatformTenant } from "@/lib/menu/platform";
import { cn } from "@/lib/utils";

export const Route = createFileRoute("/admin")({ component: PlatformAdminPage });
type Tab = "overview" | "tenants" | "leads";
const LABELS: Record<LeadStatus,string> = { new:"جديد", contacted:"تم التواصل", qualified:"مؤهل", converted:"تم التحويل", lost:"مغلق" };
const emptyPlatform = (): PlatformDashboard => ({ tenants:[], tenantCount:0, activeTenantCount:0, publishedTenantCount:0, branchCount:0, productCount:0, orderCount:0, openOrderCount:0, leadCount:0, newLeadCount:0, menuEventCount:0, activeSubscriptionCount:0, trialSubscriptionCount:0 });
const emptyLeads = (): AdminDashboard => ({ total:0,newCount:0,contactedCount:0,qualifiedCount:0,convertedCount:0,lostCount:0,leads:[] });
function fmt(v:string){try{return new Intl.DateTimeFormat("ar-SA",{dateStyle:"medium",timeStyle:"short"}).format(new Date(v))}catch{return v}}

function PlatformAdminPage(){
 const navigate=useNavigate(); const {user,isPending}=useCurrentUserState(); const [tab,setTab]=useState<Tab>("overview");
 const [platform,setPlatform]=useState<PlatformDashboard>(emptyPlatform); const [leads,setLeads]=useState<AdminDashboard>(emptyLeads); const [leadStatus,setLeadStatus]=useState<LeadStatus|"all">("all"); const [leadQuery,setLeadQuery]=useState(""); const [tenantQuery,setTenantQuery]=useState(""); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [saving,setSaving]=useState<string|null>(null);
 const tenants=useMemo(()=>{const q=tenantQuery.trim().toLowerCase();return q?platform.tenants.filter(t=>[t.nameAr,t.nameEn,t.slug,t.city,t.ownerUserId].some(v=>v.toLowerCase().includes(q))):platform.tenants},[platform.tenants,tenantQuery]);
 async function load(){setLoading(true);setError("");try{const [p,l]=await Promise.all([getPlatformDashboard(),getAdminDashboard({data:{status:leadStatus==="all"?undefined:leadStatus,q:leadQuery.trim()||undefined}})]);if(!p.ok)setError(p.error);else setPlatform(p.data);if(!l.ok)setError(c=>c||l.error);else setLeads(l.data)}catch(e){setError(e instanceof Error?e.message:"تعذر تحميل مركز المنصة")}finally{setLoading(false)}}
 useEffect(()=>{if(isPending)return;if(!user){void navigate({to:"/login",search:{redirect:"/admin"} as never,replace:true});return}void load()},[isPending,user]);
 useEffect(()=>{if(isPending||!user)return;const t=window.setTimeout(()=>void load(),220);return()=>window.clearTimeout(t)},[leadStatus,leadQuery]);
 async function toggle(t:PlatformTenant){setSaving(t.id);const r=await updatePlatformTenantStatus({data:{tenantId:t.id,isActive:!t.isActive}});if(!r.ok)setError(r.error);else setPlatform(c=>({...c,activeTenantCount:c.activeTenantCount+(r.data.isActive?1:-1),tenants:c.tenants.map(x=>x.id===t.id?{...x,isActive:r.data.isActive}:x)}));setSaving(null)}
 if(isPending||!user)return <div className="grid min-h-[60vh] place-items-center text-sm text-muted">جار التحقق من صلاحيات مالك المنصة...</div>;
 return <main className="mx-auto grid max-w-7xl gap-6 py-4 lg:py-8"><header className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><div className="mb-2 inline-flex items-center gap-2 rounded-full border border-line bg-sand/50 px-3 py-1 text-xs text-muted"><ShieldCheck className="size-3.5"/> Platform Owner</div><h1 className="font-display text-3xl font-semibold sm:text-4xl">مركز تحكم Menu V3</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-ink-soft">هذه لوحة مالك المنصة: المطاعم والعملاء والحسابات والمؤشرات. تشغيل طلبات الطعام يبقى داخل مساحة المطعم.</p></div><Button variant="outline" onClick={()=>void load()} disabled={loading}><RefreshCw className={cn("size-4",loading&&"animate-spin")}/> تحديث</Button></header>
 <nav className="grid grid-cols-3 gap-2 rounded-2xl border border-line bg-paper p-2"><Nav active={tab==="overview"} onClick={()=>setTab("overview")} icon={<LayoutDashboard className="size-4"/>}>نظرة عامة</Nav><Nav active={tab==="tenants"} onClick={()=>setTab("tenants")} icon={<Building2 className="size-4"/>}>المطاعم والعملاء</Nav><Nav active={tab==="leads"} onClick={()=>setTab("leads")} icon={<Users className="size-4"/>}>العملاء المحتملون</Nav></nav>
 {error?<div className="rounded-xl border border-line bg-sand/60 px-4 py-3 text-sm">{error}</div>:null}<section className="grid grid-cols-2 gap-3 md:grid-cols-4 xl:grid-cols-8"><K l="المطاعم" v={platform.tenantCount}/><K l="نشطة" v={platform.activeTenantCount}/><K l="منشورة" v={platform.publishedTenantCount}/><K l="الفروع" v={platform.branchCount}/><K l="الأصناف" v={platform.productCount}/><K l="الطلبات" v={platform.orderCount}/><K l="طلبات مفتوحة" v={platform.openOrderCount}/><K l="أحداث المنيو" v={platform.menuEventCount}/></section>
 {tab==="overview"?<section className="grid gap-4 md:grid-cols-3"><Card icon={<Store className="size-5"/>} title="المطاعم" text={`${platform.tenantCount} مطعم، ${platform.activeTenantCount} نشطة.`} onClick={()=>setTab("tenants")}/><Card icon={<Users className="size-5"/>} title="العملاء المحتملون" text={`${platform.newLeadCount} جديد من ${platform.leadCount}.`} onClick={()=>setTab("leads")}/><Card icon={<ShieldCheck className="size-5"/>} title="الاشتراكات" text={`${platform.activeSubscriptionCount} نشطة و${platform.trialSubscriptionCount} تجارب.`} onClick={()=>setTab("tenants")}/></section>:null}
 {tab==="tenants"?<section className="grid gap-4"><div className="rounded-2xl border border-line bg-paper p-3"><label className="relative block"><Search className="absolute start-3 top-1/2 size-4 -translate-y-1/2 text-muted"/><Input className="ps-9" value={tenantQuery} onChange={e=>setTenantQuery(e.target.value)} placeholder="ابحث باسم المطعم أو المدينة أو المعرّف"/></label></div><div className="overflow-x-auto rounded-2xl border border-line bg-paper"><table className="w-full min-w-[850px] text-sm"><thead className="bg-sand/40 text-xs text-muted"><tr>{["المطعم","الموقع","الفروع","الأصناف","الطلبات","الخطة","الحالة","إجراء"].map(x=><th key={x} className="p-4 text-start">{x}</th>)}</tr></thead><tbody>{tenants.map(t=><tr key={t.id} className="border-t border-line"><td className="p-4"><b>{t.nameAr||t.nameEn}</b><div className="text-xs text-muted">/{t.slug}</div></td><td className="p-4">{t.city||"—"} · {t.country}</td><td className="p-4">{t.branchCount}</td><td className="p-4">{t.productCount}</td><td className="p-4">{t.orderCount}</td><td className="p-4 uppercase">{t.planCode}</td><td className="p-4">{t.isActive?"نشط":"موقوف"}</td><td className="p-4"><div className="flex gap-2"><button type="button" disabled={saving===t.id} onClick={()=>void toggle(t)} className="rounded-md border border-line px-3 py-2 text-xs">{saving===t.id?"جارٍ...":t.isActive?"إيقاف":"تفعيل"}</button>{t.isPublished?<a href={`/m/${t.slug}`} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 rounded-md border border-line px-3 py-2 text-xs"><ExternalLink className="size-3"/>المنيو</a>:null}</div></td></tr>)}{!tenants.length?<tr><td colSpan={8} className="p-10 text-center text-muted">لا توجد مطاعم.</td></tr>:null}</tbody></table></div></section>:null}
 {tab==="leads"?<section className="grid gap-4"><div className="grid gap-3 rounded-2xl border border-line bg-paper p-3 md:grid-cols-[1fr_220px]"><label className="relative"><Search className="absolute start-3 top-1/2 size-4 -translate-y-1/2 text-muted"/><Input className="ps-9" value={leadQuery} onChange={e=>setLeadQuery(e.target.value)} placeholder="ابحث باسم المطعم أو المسؤول أو المدينة"/></label><select value={leadStatus} onChange={e=>setLeadStatus(e.target.value as LeadStatus|"all")} className="h-10 rounded-md border border-line bg-paper px-3 text-sm"><option value="all">كل الحالات</option>{LEAD_STATUSES.map(s=><option key={s} value={s}>{LABELS[s]}</option>)}</select></div><div className="grid gap-2">{leads.leads.map(l=><article key={l.id} className="rounded-2xl border border-line bg-paper p-4"><div className="flex flex-col gap-2 md:flex-row md:items-center md:justify-between"><div><b>{l.businessName}</b><p className="text-sm text-muted">{l.contactName} · {l.city||"—"} · {l.contactPhone}</p></div><span className="rounded-full bg-sand px-2.5 py-1 text-xs">{LABELS[l.status]}</span></div><div className="mt-2 text-xs text-muted">{fmt(l.createdAt)}{l.details?` · ${l.details}`:""}</div></article>)}{!leads.leads.length?<div className="rounded-2xl border border-dashed border-line p-10 text-center text-muted">لا توجد نتائج.</div>:null}</div></section>:null}
 </main>
}
function Nav({active,onClick,icon,children}:{active:boolean;onClick:()=>void;icon:React.ReactNode;children:React.ReactNode}){return <button type="button" onClick={onClick} className={cn("inline-flex h-10 items-center justify-center gap-2 rounded-xl text-sm",active?"bg-ink text-paper":"text-muted hover:bg-sand/50")}>{icon}{children}</button>}
function K({l,v}:{l:string;v:number}){return <div className="grid gap-1 rounded-2xl border border-line bg-paper p-4"><span className="text-xs text-muted">{l}</span><strong className="text-2xl">{v.toLocaleString("ar-SA")}</strong></div>}
function Card({icon,title,text,onClick}:{icon:React.ReactNode;title:string;text:string;onClick:()=>void}){return <article className="grid gap-4 rounded-2xl border border-line bg-paper p-5"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-sand/60">{icon}</span><h2 className="font-semibold">{title}</h2></div><p className="text-sm leading-6 text-muted">{text}</p><Button variant="outline" onClick={onClick}>فتح</Button></article>}
