import { useMemo, useState } from "react";
import { ArrowUpLeft, BarChart3, Check, ExternalLink, GitBranch, Globe2, Layers3, Menu, QrCode, ScanLine, Sparkles, Smartphone, Store, X } from "lucide-react";
import { createFileRoute, Link } from "@tanstack/react-router";
import { LangToggle } from "@/components/lang-toggle";
import { Button } from "@/components/ui/button";
import { useLang } from "@/lib/lang";
import { COMMERCIAL_FEATURES, COMMERCIAL_PLANS } from "@/lib/menu/commercial-catalog";
import { MENU_THEMES } from "@/lib/theme";
import "./index.css";

export const Route = createFileRoute("/")({ component: Home });
const FEATURES = [
  { icon: QrCode, ar: "منيو رقمي", en: "Digital menu", bodyAr: "منيو جذاب وسهل المشاركة عبر QR ورابط مباشر.", bodyEn: "A polished menu that is easy to share by QR and public link." },
  { icon: Smartphone, ar: "تجربة جوال", en: "Mobile experience", bodyAr: "تجربة سريعة وواضحة للضيف على أي هاتف.", bodyEn: "A fast, clear guest experience on every phone." },
  { icon: BarChart3, ar: "تحليلات واضحة", en: "Actionable analytics", bodyAr: "افهم الزيارات ومشاهدات الأصناف وما يهم ضيوفك.", bodyEn: "Understand visits, product views, and what guests care about." },
  { icon: GitBranch, ar: "إدارة فروع", en: "Branch management", bodyAr: "إدارة الفروع ضمن حدود الباقة وبسياق واضح.", bodyEn: "Branch-aware management within your plan limits." },
  { icon: Globe2, ar: "عربي وإنجليزي", en: "Arabic & English", bodyAr: "RTL/LTR مصمم من الأساس، وليس إضافة لاحقة.", bodyEn: "Intentional RTL/LTR support from the foundation." },
  { icon: Sparkles, ar: "تحديث سريع", en: "Fast updates", bodyAr: "حدّث السعر أو الصنف وانشر دون إعادة طباعة المنيو.", bodyEn: "Update a price or product without reprinting the menu." },
] as const;
const STEPS = [
  { n: "01", icon: Store, ar: "أنشئ حسابك", en: "Create your account", bodyAr: "أدخل بياناتك الأساسية ثم انتقل مباشرة لإعداد مساحة مطعمك.", bodyEn: "Enter your essentials, then go directly to workspace setup." },
  { n: "02", icon: Layers3, ar: "أضف المنيو والفروع", en: "Add menu & branches", bodyAr: "رتّب الأصناف والأسعار والفروع.", bodyEn: "Organize products, prices, and branches." },
  { n: "03", icon: ScanLine, ar: "شارك QR والرابط", en: "Share QR & link", bodyAr: "ضع التجربة أمام ضيوفك خلال دقائق.", bodyEn: "Put the experience in front of guests in minutes." },
] as const;
const FAQS = [
  { qAr: "هل أحتاج خبرة تقنية؟", qEn: "Do I need technical experience?", aAr: "لا. صُممت المنصة لإدارة المنيو من واجهة واضحة دون كتابة كود.", aEn: "No. Restaurant teams can manage the menu through a clear interface without writing code." },
  { qAr: "هل يدعم العربية والإنجليزية؟", qEn: "Does it support Arabic and English?", aAr: "نعم. Menu V3 عربي أولاً مع دعم الإنجليزية وRTL/LTR.", aEn: "Yes. Menu V3 is Arabic-first with English and RTL/LTR support." },
  { qAr: "هل أستطيع إدارة أكثر من فرع؟", qEn: "Can I manage multiple branches?", aAr: "نعم، ضمن حدود الباقة المختارة.", aEn: "Yes, within the selected plan limits." },
  { qAr: "هل يمكن تحديث الأسعار فوراً؟", qEn: "Can I update prices immediately?", aAr: "نعم، بعد نشر التعديل عبر مسار المحتوى العام في المنصة.", aEn: "Yes, after publishing through the platform's public-content path." },
  { qAr: "هل يوجد رابط عام للمنيو؟", qEn: "Is there a public menu link?", aAr: "نعم، ويمكن استخدامه مع QR والمشاركة المباشرة.", aEn: "Yes, and it can be used with QR and direct sharing." },
] as const;

function Home() {
  const { lang } = useLang();
  const [mobileOpen, setMobileOpen] = useState(false);
  const themeCards = useMemo(() => MENU_THEMES.map((theme) => ({ ...theme })), []);
  const signup = <Link to="/login" search={{ mode: "signup" } as never}>{lang === "ar" ? "ابدأ مجانًا" : "Start free"}</Link>;
  const navItems = [["#features", lang === "ar" ? "المميزات" : "Features"], ["#themes", lang === "ar" ? "التصاميم" : "Themes"], ["#how", lang === "ar" ? "كيف تعمل" : "How it works"], ["#pricing", lang === "ar" ? "الباقات" : "Pricing"], ["#faq", lang === "ar" ? "الأسئلة الشائعة" : "FAQ"]] as const;
  return <main className="menuq-home min-h-screen bg-background text-foreground">
    <header className="sticky top-0 z-50 border-b bg-background/95 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between px-4 py-3 sm:px-6"><Link to="/" className="font-semibold tracking-tight">Menu V3</Link><nav className="hidden items-center gap-6 md:flex">{navItems.map(([href, label]) => <a key={href} href={href} className="text-sm text-muted-foreground transition hover:text-foreground">{label}</a>)}</nav><div className="flex items-center gap-2"><LangToggle /><Button asChild size="sm"><Link to="/login">{lang === "ar" ? "دخول" : "Sign in"}</Link></Button><button type="button" aria-label={lang === "ar" ? "فتح القائمة" : "Open menu"} className="rounded-md p-2 md:hidden" onClick={() => setMobileOpen((value) => !value)}>{mobileOpen ? <X size={20} /> : <Menu size={20} />}</button></div></div>{mobileOpen && <nav className="border-t px-4 py-3 md:hidden">{navItems.map(([href, label]) => <a key={href} href={href} onClick={() => setMobileOpen(false)} className="block py-2 text-sm">{label}</a>)}</nav>}</header>
    <section className="relative overflow-hidden px-4 pb-20 pt-16 sm:px-6 sm:pt-24"><div className="mx-auto grid max-w-7xl items-center gap-12 lg:grid-cols-[1.05fr_.95fr]"><div className="max-w-3xl"><div className="mb-5 inline-flex items-center gap-2 rounded-full border px-3 py-1 text-xs font-medium"><Sparkles size={14} />{lang === "ar" ? "منيو رقمي عربي أولاً" : "Arabic-first digital menus"}</div><h1 className="menuq-display text-5xl sm:text-6xl lg:text-7xl">{lang === "ar" ? "حوّل منيو مطعمك إلى تجربة تستحق الزيارة." : "Turn your restaurant menu into an experience worth visiting."}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-muted-foreground">{lang === "ar" ? "Menu V3 يمنح المطاعم والكافيهات منيو سريعاً، أنيقاً، ثنائي اللغة، ومصمماً للجوال من أول لمسة." : "Menu V3 gives restaurants and cafés a fast, elegant, bilingual menu designed mobile-first from the first tap."}</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Button asChild size="lg">{signup}<ArrowUpLeft className="ms-2" size={18} /></Button><Button asChild size="lg" variant="outline"><Link to="/themes/preview">{lang === "ar" ? "شاهد التصاميم" : "Explore themes"}<ExternalLink className="ms-2" size={17} /></Link></Button></div><div className="mt-8 grid max-w-xl grid-cols-3 gap-4 text-sm"><div><strong className="block text-xl">5</strong><span className="text-muted-foreground">{lang === "ar" ? "تصاميم" : "Themes"}</span></div><div><strong className="block text-xl">RTL</strong><span className="text-muted-foreground">{lang === "ar" ? "من الأساس" : "Native"}</span></div><div><strong className="block text-xl">QR</strong><span className="text-muted-foreground">{lang === "ar" ? "ومشاركة" : "& sharing"}</span></div></div></div><div className="menuq-hero-preview mx-auto w-full max-w-xl"><div className="menuq-phone mx-auto max-w-sm"><div className="menuq-phone-screen p-5"><div className="flex items-center justify-between text-xs text-muted-foreground"><span>Menu V3</span><span>● Open</span></div><div className="mt-12"><p className="text-xs uppercase tracking-[.22em] text-muted-foreground">Restaurant</p><h2 className="mt-2 text-4xl font-semibold">Taste your story.</h2><p className="mt-3 text-sm text-muted-foreground">{lang === "ar" ? "قائمة مختارة بعناية" : "A carefully curated menu"}</p></div><div className="mt-10 grid grid-cols-2 gap-3"><div className="menuq-food gold aspect-square rounded-2xl" /><div className="menuq-food green aspect-square rounded-2xl" /></div></div></div></div></div></section>
    <section id="features" className="border-y bg-muted/30 px-4 py-20 sm:px-6"><div className="mx-auto max-w-7xl"><p className="menuq-eyebrow">{lang === "ar" ? "مصمم للمطاعم" : "BUILT FOR RESTAURANTS"}</p><h2 className="menuq-section-title mt-3">{lang === "ar" ? "كل ما يحتاجه المنيو الحديث، في تجربة واحدة." : "Everything a modern menu needs, in one experience."}</h2><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{FEATURES.map(({ icon: Icon, ar, en, bodyAr, bodyEn }) => <article key={en} className="menuq-card"><Icon size={22} /><h3 className="mt-5 text-lg font-semibold">{lang === "ar" ? ar : en}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{lang === "ar" ? bodyAr : bodyEn}</p></article>)}</div></div></section>
    <section id="themes" className="px-4 py-20 sm:px-6"><div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="menuq-eyebrow">{lang === "ar" ? "هوية قبل القالب" : "IDENTITY BEFORE TEMPLATE"}</p><h2 className="menuq-section-title mt-3">{lang === "ar" ? "اختر الأسلوب الذي يشبه مطعمك." : "Choose the style that fits your restaurant."}</h2></div><Button asChild variant="outline"><Link to="/themes/preview">{lang === "ar" ? "معاينة كاملة" : "Full preview"}</Link></Button></div><div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{themeCards.map((theme) => <article key={theme.key} className="menuq-card overflow-hidden p-0"><div className="aspect-[4/3] overflow-hidden bg-muted"><img src={theme.preview.image} alt="" className="h-full w-full object-cover transition duration-500 hover:scale-105" loading="lazy" /></div><div className="p-5"><div className="flex items-center justify-between gap-3"><h3 className="text-xl font-semibold">{lang === "ar" ? theme.name.ar : theme.name.en}</h3><span className="text-xs text-muted-foreground">{theme.key}</span></div><p className="mt-2 text-sm leading-6 text-muted-foreground">{lang === "ar" ? theme.promise.ar : theme.promise.en}</p><Button asChild className="mt-5 w-full" variant="outline">{signup}</Button></div></article>)}</div></div></section>
    <section id="how" className="bg-foreground px-4 py-20 text-background sm:px-6"><div className="mx-auto max-w-7xl"><h2 className="max-w-2xl text-3xl font-semibold sm:text-4xl">{lang === "ar" ? "من الحساب إلى QR خلال خطوات واضحة." : "From account to QR in three clear steps."}</h2><div className="mt-10 grid gap-4 md:grid-cols-3">{STEPS.map(({ n, icon: Icon, ar, en, bodyAr, bodyEn }) => <article key={n} className="rounded-2xl border border-background/15 p-6"><div className="flex items-center justify-between"><span className="text-sm opacity-60">{n}</span><Icon size={22} /></div><h3 className="mt-12 text-xl font-semibold">{lang === "ar" ? ar : en}</h3><p className="mt-2 text-sm leading-6 opacity-70">{lang === "ar" ? bodyAr : bodyEn}</p></article>)}</div></div></section>
    <section id="pricing" className="px-4 py-20 sm:px-6"><div className="mx-auto max-w-7xl"><p className="menuq-eyebrow">{lang === "ar" ? "باقات واضحة" : "SIMPLE PLANS"}</p><h2 className="menuq-section-title mt-3">{lang === "ar" ? "ابدأ بما يناسب حجم عملك." : "Start with the plan that fits your business."}</h2><div className="mt-10 grid gap-5 md:grid-cols-3">{COMMERCIAL_PLANS.map((plan) => <article key={plan.code} className={`menuq-card ${plan.recommended ? "ring-2 ring-foreground" : ""}`}><div className="flex items-center justify-between gap-3"><h3 className="text-xl font-semibold">{lang === "ar" ? plan.nameAr : plan.nameEn}</h3>{plan.recommended && <span className="rounded-full border px-2 py-1 text-[10px]">{lang === "ar" ? "موصى به" : "Recommended"}</span>}</div><div className="mt-5 text-4xl font-semibold">{plan.monthlyPriceSar}<span className="text-sm font-normal text-muted-foreground"> {lang === "ar" ? "ريال / شهر" : "SAR / month"}</span></div><ul className="mt-6 space-y-3 text-sm"><li className="flex gap-2"><Check size={17} />{lang === "ar" ? `${plan.maxBranches} فرع` : `${plan.maxBranches} branch${plan.maxBranches === 1 ? "" : "es"}`}</li><li className="flex gap-2"><Check size={17} />{lang === "ar" ? `${plan.maxProducts.toLocaleString("ar-SA")} صنف` : `${plan.maxProducts.toLocaleString("en-US")} products`}</li><li className="flex gap-2"><Check size={17} />{lang === "ar" ? `${plan.maxTeamMembers} أعضاء فريق` : `${plan.maxTeamMembers} team members`}</li></ul><Button asChild className="mt-7 w-full">{signup}</Button></article>)}</div><div className="menuq-card mt-8"><p className="font-medium">{lang === "ar" ? "يشمل نظام المنيو" : "Menu system highlights"}</p><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{COMMERCIAL_FEATURES[lang].map((feature) => <div key={feature} className="flex gap-2 text-sm text-muted-foreground"><Check size={16} className="shrink-0" />{feature}</div>)}</div></div></div></section>
    <section className="border-y bg-muted/30 px-4 py-20 sm:px-6"><div className="mx-auto grid max-w-7xl items-center gap-8 rounded-3xl border bg-background p-7 md:grid-cols-[1fr_auto] md:p-10"><div><p className="menuq-eyebrow">{lang === "ar" ? "بدون طلبات انتظار" : "NO APPROVAL QUEUE"}</p><h2 className="menuq-section-title mt-3">{lang === "ar" ? "أنشئ حسابك وابدأ مباشرة." : "Create your account and start directly."}</h2><p className="mt-3 max-w-2xl leading-7 text-muted-foreground">{lang === "ar" ? "لا تحتاج إلى إرسال طلب أو انتظار اعتماد. التسجيل ينشئ الحساب، وبعدها تجهّز مساحة مطعمك وتدخل إلى الاستوديو." : "No request form and no approval queue. Sign up, set up your restaurant workspace, and enter Studio."}</p></div><Button asChild size="lg">{signup}<ArrowUpLeft className="ms-2" size={18} /></Button></div></section>
    <section id="faq" className="px-4 py-20 sm:px-6"><div className="mx-auto max-w-4xl"><p className="menuq-eyebrow">FAQ</p><h2 className="menuq-section-title mt-3">{lang === "ar" ? "أسئلة قبل البدء." : "Questions before you start."}</h2><div className="mt-8 divide-y rounded-2xl border">{FAQS.map(({ qAr, qEn, aAr, aEn }) => <details key={qEn} className="group p-5"><summary className="flex cursor-pointer list-none items-center justify-between gap-4 font-medium"><span>{lang === "ar" ? qAr : qEn}</span><span>⌄</span></summary><p className="mt-3 text-sm leading-7 text-muted-foreground">{lang === "ar" ? aAr : aEn}</p></details>)}</div></div></section>
    <footer className="border-t px-4 py-10 sm:px-6"><div className="mx-auto flex max-w-7xl flex-col gap-4 text-sm text-muted-foreground sm:flex-row sm:items-center sm:justify-between"><span className="font-medium text-foreground">Menu V3</span><span>{lang === "ar" ? "منيو رقمي عربي أولاً للمطاعم والكافيهات." : "Arabic-first digital menus for restaurants and cafés."}</span><div className="flex gap-4"><Link to="/themes/preview" className="hover:text-foreground">{lang === "ar" ? "التصاميم" : "Themes"}</Link><Link to="/pricing" className="hover:text-foreground">{lang === "ar" ? "الأسعار" : "Pricing"}</Link></div></div></footer>
  </main>;
}
