import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { Field, Input } from "@/components/ui/input";
import { getProductOffer, saveProductOffer, deleteProductOffer } from "@/lib/menu/offers-api";
import { isoToRiyadhLocal } from "@/lib/menu/offers";
import type { Lang, OfferType, ProductOffer } from "@/lib/menu/types";
const text=(lang:Lang,ar:string,en:string)=>lang==="ar"?ar:en;
export function ProductOfferPanel({productId,lang,disabled=false}:{productId:string;lang:Lang;disabled?:boolean}){
 const[offer,setOffer]=useState<ProductOffer|null>(null),[type,setType]=useState<OfferType>("percentage"),[value,setValue]=useState(""),[labelAr,setLabelAr]=useState(""),[labelEn,setLabelEn]=useState(""),[startsAt,setStartsAt]=useState(""),[endsAt,setEndsAt]=useState(""),[active,setActive]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState("");
 useEffect(()=>{getProductOffer({data:{productId}}).then(result=>{if(!result.ok){setError(result.error);return;}if(result.data){setOffer(result.data);setType(result.data.offerType);setValue(result.data.value==null?"":String(result.data.value));setLabelAr(result.data.labelAr);setLabelEn(result.data.labelEn);setStartsAt(isoToRiyadhLocal(result.data.startsAt));setEndsAt(isoToRiyadhLocal(result.data.endsAt));setActive(result.data.isActive);}}).catch(()=>setError(text(lang,"تعذر تحميل العرض","Could not load offer")))},[productId,lang]);
 async function save(){setBusy(true);setError("");const result=await saveProductOffer({data:{id:offer?.id,productId,offerType:type,value:type==="bogo"?null:Number(value||0),labelAr,labelEn,startsAt,endsAt,isActive:active}});if(!result.ok)setError(result.error);else setOffer(result.data);setBusy(false)}
 async function remove(){if(!offer)return;setBusy(true);const result=await deleteProductOffer({data:{id:offer.id,productId}});if(!result.ok)setError(result.error);else setOffer(null);setBusy(false)}
 return <section className="grid gap-3 rounded-xl border border-line bg-sand/20 p-3"><div><p className="text-sm font-semibold">{text(lang,"العروض والتخفيضات","Offers & promotions")}</p><p className="text-xs text-muted">{text(lang,"عرض فعّال واحد كحد أقصى لكل صنف. التوقيت Asia/Riyadh.","Maximum one active offer per item. Time zone: Asia/Riyadh.")}</p></div>{error?<p className="text-xs text-bad"role="alert">{error}</p>:null}<div className="grid gap-2 sm:grid-cols-2"><label className="grid gap-1 text-xs"><span>{text(lang,"نوع العرض","Offer type")}</span><select value={type}onChange={event=>setType(event.target.value as OfferType)}className="h-10 rounded-lg border border-line bg-paper px-2"><option value="percentage">{text(lang,"نسبة مئوية","Percentage off")}</option><option value="fixed">{text(lang,"خصم مبلغ ثابت","Fixed amount off")}</option><option value="sale_price">{text(lang,"سعر بيع خاص","Sale price")}</option><option value="bogo">BOGO</option></select></label>{type!=="bogo"?<Field label={type==="percentage"?text(lang,"النسبة %","Percent"):text(lang,"القيمة","Value")}><Input inputMode="decimal"value={value}onChange={event=>setValue(event.target.value)}/></Field>:null}</div><div className="grid gap-2 sm:grid-cols-2"><Field label={text(lang,"العنوان العربي","Arabic label")}><Input value={labelAr}onChange={event=>setLabelAr(event.target.value)}/></Field><Field label={text(lang,"العنوان الإنجليزي","English label")}><Input value={labelEn}onChange={event=>setLabelEn(event.target.value)}/></Field></div><div className="grid gap-2 sm:grid-cols-2"><Field label={text(lang,"يبدأ بتوقيت الرياض","Starts (Riyadh time)")}><Input type="datetime-local"value={startsAt}onChange={event=>setStartsAt(event.target.value)}/></Field><Field label={text(lang,"ينتهي بتوقيت الرياض","Ends (Riyadh time)")}><Input type="datetime-local"value={endsAt}onChange={event=>setEndsAt(event.target.value)}/></Field></div><label className="flex min-h-10 items-center gap-2 text-sm"><input type="checkbox"checked={active}onChange={event=>setActive(event.target.checked)}/>{text(lang,"فعّال","Active")}</label><div className="flex flex-wrap gap-2"><Button type="button"disabled={busy||disabled}onClick={()=>void save()}>{text(lang,"حفظ العرض","Save offer")}</Button>{offer?<Button type="button"variant="danger"disabled={busy||disabled}onClick={()=>void remove()}>{text(lang,"حذف العرض","Delete offer")}</Button>:null}</div></section>;
}
