import { useEffect, useState } from "react";
import { ChevronDown, ChevronUp } from "lucide-react";
import { listProductOptions, reorderProductOption } from "@/lib/menu/options";
import type { Lang, ModifierGroup, ModifierOption, ProductVariant } from "@/lib/menu/types";
const text=(lang:Lang,ar:string,en:string)=>lang==="ar"?ar:en;
export function ProductOptionsOrderingPanel({productId,lang,disabled=false}:{productId:string;lang:Lang;disabled?:boolean}){
 const [variants,setVariants]=useState<ProductVariant[]>([]),[groups,setGroups]=useState<ModifierGroup[]>([]),[options,setOptions]=useState<ModifierOption[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState("");
 async function refresh(){const r=await listProductOptions({data:{productId}});if(!r.ok){setError(r.error);return;}setVariants(r.data.variants);setGroups(r.data.groups);setOptions(r.data.options);}
 useEffect(()=>{void refresh()},[productId]);
 async function move(type:"variant"|"group"|"option",id:string,groupId?:string,direction:"up"|"down"="up"){if(disabled||busy)return;setBusy(true);setError("");const r=await reorderProductOption({data:{productId,type,id,groupId,direction}});if(!r.ok)setError(r.error);else await refresh();setBusy(false);}
 const arrows=(type:"variant"|"group"|"option",id:string,index:number,length:number,groupId?:string)=><span className="flex gap-1"><button type="button"disabled={disabled||busy||index===0}onClick={()=>void move(type,id,groupId,"up")}aria-label={text(lang,"تحريك للأعلى","Move up")}className="grid size-9 place-items-center rounded-lg border border-line disabled:opacity-40"><ChevronUp className="size-4"/></button><button type="button"disabled={disabled||busy||index===length-1}onClick={()=>void move(type,id,groupId,"down")}aria-label={text(lang,"تحريك للأسفل","Move down")}className="grid size-9 place-items-center rounded-lg border border-line disabled:opacity-40"><ChevronDown className="size-4"/></button></span>;
 return <section className="grid gap-3 rounded-xl border border-line bg-sand/20 p-3"><div><p className="text-sm font-semibold">{text(lang,"ترتيب خيارات الصنف","Item option order")}</p><p className="text-xs text-muted">{text(lang,"الخيارات محفوظة على مستوى المطعم لأنها ليست مرتبطة بفرع.","Options are tenant-scoped because they are not branch-specific.")}</p></div>{error?<p className="text-xs text-bad"role="alert">{error}</p>:null}{variants.length?<div className="grid gap-2"><p className="text-xs font-medium">{text(lang,"الأحجام / المتغيرات","Variants")}</p>{variants.map((item,index)=><div key={item.id}className="flex items-center justify-between gap-2 rounded-lg border border-line bg-paper px-3 py-2"><span className="truncate text-sm">{text(lang,item.nameAr,item.nameEn||item.nameAr)}</span>{arrows("variant",item.id,index,variants.length)}</div>)}</div>:null}{groups.map((group,index)=><div key={group.id}className="grid gap-2 rounded-lg border border-line bg-paper p-2"><div className="flex items-center justify-between gap-2"><span className="truncate text-sm font-medium">{text(lang,group.nameAr,group.nameEn||group.nameAr)}</span>{arrows("group",group.id,index,groups.length)}</div>{options.filter(option=>option.groupId===group.id).map((option,optionIndex)=>{const groupOptions=options.filter(candidate=>candidate.groupId===group.id);return <div key={option.id}className="ms-3 flex items-center justify-between gap-2 rounded-lg border border-line bg-sand/30 px-3 py-2"><span className="truncate text-xs">{text(lang,option.nameAr,option.nameEn||option.nameAr)}</span>{arrows("option",option.id,optionIndex,groupOptions.length,group.id)}</div>})}</div>)}{!variants.length&&!groups.length?<p className="text-xs text-muted">{text(lang,"لا توجد خيارات محفوظة لهذا الصنف بعد.","No saved options for this item yet.")}</p>:null}</section>;
}
