import { forwardRef, useEffect, useMemo, useRef, useState } from "react";
import { ArrowLeft, ArrowRight, CheckCircle2, Clock3, ExternalLink, PackageCheck, Phone, RefreshCw, Search, ShieldAlert, UserRound, XCircle } from "lucide-react";
import { createFileRoute, useNavigate, useRouterState } from "@tanstack/react-router";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { useLang } from "@/lib/lang";
import { getOrdersDashboard, ORDER_STATUSES, updateOrderStatus, type AdminOrder, type OrderStatus, type OrdersDashboard } from "@/lib/menu/orders";
import { buildOrderContact, buildOrderWhatsAppUrl } from "@/lib/menu/order-contact";
import { t } from "@/lib/menu/i18n";
import { cn } from "@/lib/utils";

export const Route = createFileRoute("/studio/orders")({ component: OrdersPage });

type Copy = { ar: string; en: string };
const C: Record<string, Copy> = {
  eyebrow:{ar:"مساحة تشغيل الطلبات",en:"Order operations"}, title:{ar:"الطلبات",en:"Orders"}, intro:{ar:"راجع الطلبات واتخذ الإجراء التالي بسرعة، مع الحفاظ على بيانات الطلب كما سُجلت فعلياً.",en:"Review orders and take the next operational action without changing recorded order data."},
  refresh:{ar:"تحديث",en:"Refresh"}, all:{ar:"كل الطلبات",en:"All orders"}, new:{ar:"جديدة",en:"New"}, active:{ar:"نشطة",en:"Active"}, completed:{ar:"مكتملة",en:"Completed"},
  search:{ar:"اسم العميل أو الجوال أو رقم الطلب",en:"Customer, phone, or order number"}, allStatus:{ar:"كل الحالات",en:"All statuses"}, empty:{ar:"لا توجد طلبات لهذا النشاط حتى الآن.",en:"No orders are available for this business yet."}, loading:{ar:"جارٍ تحميل الطلبات…",en:"Loading orders…"}, select:{ar:"اختر طلباً لعرض تفاصيله.",en:"Select an order to view its details."},
  customer:{ar:"العميل",en:"Customer"}, branch:{ar:"الفرع",en:"Branch"}, source:{ar:"المصدر",en:"Source"}, created:{ar:"تاريخ الإنشاء",en:"Created"}, contact:{ar:"تواصل مع العميل",en:"Contact customer"}, phone:{ar:"الجوال",en:"Phone"}, email:{ar:"البريد الإلكتروني",en:"Email"}, total:{ar:"الإجمالي",en:"Total"}, notes:{ar:"ملاحظات الطلب",en:"Order notes"}, items:{ar:"الأصناف",en:"Items"}, change:{ar:"تغيير الحالة",en:"Change status"}, apply:{ar:"تطبيق الحالة",en:"Apply status"}, cancel:{ar:"إلغاء الطلب",en:"Cancel order"}, confirmCancel:{ar:"تأكيد إلغاء الطلب؟",en:"Cancel this order?"}, cancelBody:{ar:"سيتم تسجيل الحالة كملغاة عبر مسار الحالة الموجود في النظام.",en:"The order will be recorded as cancelled through the existing status path."}, keep:{ar:"العودة",en:"Keep order"}, confirm:{ar:"تأكيد",en:"Confirm"}, whatsapp:{ar:"واتساب",en:"WhatsApp"}, call:{ar:"اتصال",en:"Call"}, noPhone:{ar:"لا يوجد رقم جوال صالح للتواصل مع العميل.",en:"No valid customer phone number is available."}, noNotes:{ar:"لا توجد ملاحظات مسجلة لهذا الطلب.",en:"No order notes are recorded."}, back:{ar:"العودة إلى قائمة الطلبات",en:"Back to orders"}, customerFallback:{ar:"عميل",en:"Customer"}, itemFallback:{ar:"صنف",en:"Item"}, next:{ar:"الإجراء التالي",en:"Next action"},
};
const STATUS: Record<OrderStatus, Copy> = { new:{ar:"جديد",en:"New"}, confirmed:{ar:"مؤكد",en:"Confirmed"}, preparing:{ar:"قيد التحضير",en:"Preparing"}, ready:{ar:"جاهز",en:"Ready"}, completed:{ar:"مكتمل",en:"Completed"}, cancelled:{ar:"ملغى",en:"Cancelled"} };
const NEXT: Partial<Record<OrderStatus,OrderStatus>> = { new:"confirmed", confirmed:"preparing", preparing:"ready", ready:"completed" };
const NEXT_LABEL: Record<OrderStatus,Copy> = { new:{ar:"تأكيد الطلب",en:"Confirm order"}, confirmed:{ar:"بدء التحضير",en:"Start preparing"}, preparing:{ar:"تحديد كجاهز",en:"Mark ready"}, ready:{ar:"إتمام / تسليم الطلب",en:"Complete / hand over"}, completed:{ar:"عرض تفاصيل الطلب",en:"View order details"}, cancelled:{ar:"عرض تفاصيل الطلب",en:"View order details"} };
const empty: OrdersDashboard = { total:0,newCount:0,activeCount:0,completedCount:0,cancelledCount:0,orders:[] };
const text = (v: Copy, lang: "ar"|"en") => t(v, lang);

function money(value:number,currency:string,lang:"ar"|"en") { try { return new Intl.NumberFormat(lang === "ar" ? "ar-SA" : "en-SA",{style:"currency",currency,currencyDisplay:"code",maximumFractionDigits:2}).format(value); } catch { return `${value.toFixed(2)} ${currency}`; } }
function date(value:string,lang:"ar"|"en") { try { return new Intl.DateTimeFormat(lang === "ar" ? "ar-SA" : "en-SA",{dateStyle:"medium",timeStyle:"short"}).format(new Date(value)); } catch { return value; } }
function source(value:string,lang:"ar"|"en") { const map:Record<string,Copy>={web:{ar:"المنيو",en:"Menu"},whatsapp:{ar:"واتساب",en:"WhatsApp"},manual:{ar:"يدوي",en:"Manual"},qr:{ar:"QR",en:"QR"}}; return text(map[value] ?? {ar:value,en:value},lang); }

function OrdersPage() {
  const { lang } = useLang(); const navigate = useNavigate(); const searchStr = useRouterState({select:s=>s.location.searchStr});
  const orderId = useMemo(()=>new URLSearchParams(searchStr).get("order"),[searchStr]);
  const [data,setData]=useState(empty); const [status,setStatus]=useState<OrderStatus|"all">("all"); const [query,setQuery]=useState(""); const [selected,setSelected]=useState<AdminOrder|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
  const detailRef=useRef<HTMLElement|null>(null); const listRef=useRef<HTMLElement|null>(null);
  async function load(){ setLoading(true); setError(""); try { const r=await getOrdersDashboard({data:{status:status === "all" ? undefined : status,q:query.trim()||undefined}}); if(!r.ok)setError(r.error); else setData(r.data); } catch(e){setError(e instanceof Error?e.message:text(C.noPhone,lang));} finally{setLoading(false);} }
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),180);return()=>window.clearTimeout(timer);},[status,query]);
  useEffect(()=>{ if(!data.orders.length){setSelected(null);return;} if(!orderId){setSelected(null);return;} setSelected(data.orders.find(o=>o.id===orderId) ?? null); },[data.orders,orderId]);
  async function selectOrder(order:AdminOrder){ const current=Object.fromEntries(new URLSearchParams(searchStr).entries()); await navigate({search:{...current,order:order.id} as never,replace:false}); window.requestAnimationFrame(()=>detailRef.current?.scrollIntoView({behavior:"smooth",block:"start"})); }
  async function back(){const current=Object.fromEntries(new URLSearchParams(searchStr).entries());delete current.order;await navigate({search:current as never,replace:false});window.requestAnimationFrame(()=>listRef.current?.scrollIntoView({behavior:"smooth",block:"start"}));}
  async function changeStatus(id:string,next:OrderStatus){const r=await updateOrderStatus({data:{id,status:next}});if(!r.ok)setError(r.error);else{setData(d=>({...d,orders:d.orders.map(o=>o.id===id?r.data:o)}));setSelected(r.data);}}
  return <main className="mx-auto grid min-w-0 max-w-7xl gap-5 py-4 lg:py-8">
    <header className="grid gap-4 rounded-3xl border border-line bg-paper p-5 md:p-7 lg:grid-cols-[1fr_auto] lg:items-end"><div className="min-w-0"><p className="text-xs font-semibold uppercase tracking-[.18em] text-accent">{text(C.eyebrow,lang)}</p><h1 className="mt-2 font-display text-3xl font-semibold">{text(C.title,lang)}</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-muted">{text(C.intro,lang)}</p></div><Button variant="outline" onClick={()=>void load()} disabled={loading} aria-label={text(C.refresh,lang)}><RefreshCw className={cn("size-4",loading&&"animate-spin")}/>{text(C.refresh,lang)}</Button></header>
    <section aria-label={lang === "ar" ? "ملخص الطلبات" : "Orders summary"} className="grid grid-cols-2 gap-3 md:grid-cols-4"><Kpi icon={<PackageCheck className="size-4"/>} label={text(C.all,lang)} value={data.total} lang={lang}/><Kpi icon={<Clock3 className="size-4"/>} label={text(C.new,lang)} value={data.newCount} lang={lang}/><Kpi icon={<Clock3 className="size-4"/>} label={text(C.active,lang)} value={data.activeCount} lang={lang}/><Kpi icon={<CheckCircle2 className="size-4"/>} label={text(C.completed,lang)} value={data.completedCount} lang={lang}/></section>
    {error?<div role="alert" className="rounded-2xl border border-danger/40 bg-danger/10 p-4 text-sm">{error}</div>:null}
    <section ref={listRef} className="grid min-w-0 gap-4 rounded-3xl border border-line bg-sand/20 p-3 md:p-4 lg:grid-cols-[1.1fr_.9fr]"><div className="grid min-w-0 content-start gap-3"><div className="grid min-w-0 gap-2 md:grid-cols-[1fr_190px]"><label className="relative min-w-0"><Search className="pointer-events-none absolute start-3 top-1/2 size-4 -translate-y-1/2 text-muted"/><span className="sr-only">{text(C.search,lang)}</span><Input className="ps-9" value={query} onChange={e=>setQuery(e.target.value)} placeholder={text(C.search,lang)} aria-label={text(C.search,lang)}/></label><label className="grid min-w-0"><span className="sr-only">{text(C.allStatus,lang)}</span><select aria-label={text(C.allStatus,lang)} value={status} onChange={e=>setStatus(e.target.value as OrderStatus|"all")} className="h-10 min-w-0 rounded-md border border-line bg-paper px-3 text-sm"><option value="all">{text(C.allStatus,lang)}</option>{ORDER_STATUSES.map(s=><option key={s} value={s}>{text(STATUS[s],lang)}</option>)}</select></label></div>{loading&&!data.orders.length?<Empty text={text(C.loading,lang)}/>:!data.orders.length?<Empty text={text(C.empty,lang)}/>:data.orders.map(order=><OrderList key={order.id} order={order} selected={selected?.id===order.id} lang={lang} onSelect={()=>void selectOrder(order)}/>)}</div><OrderDetail ref={detailRef} order={selected} lang={lang} onBack={back} onStatus={changeStatus}/></section>
  </main>;
}
function Kpi({icon,label,value,lang}:{icon:React.ReactNode;label:string;value:number;lang:"ar"|"en"}){return <div className="rounded-2xl border border-line bg-paper p-4"><span className="flex items-center gap-2 text-xs text-muted">{icon}{label}</span><strong className="mt-1 block text-2xl tabular-nums" dir="ltr">{value.toLocaleString(lang === "ar" ? "ar-SA":"en-SA")}</strong></div>}
function Badge({status,lang}:{status:OrderStatus;lang:"ar"|"en"}){return <span className="rounded-full bg-sand px-2.5 py-1 text-xs">{text(STATUS[status],lang)}</span>}
function Empty({text:value}:{text:string}){return <div className="rounded-2xl border border-dashed border-line p-10 text-center text-sm text-muted">{value}</div>}
function OrderList({order,selected,lang,onSelect}:{order:AdminOrder;selected:boolean;lang:"ar"|"en";onSelect:()=>void}){const customer=order.customerName||text(C.customerFallback,lang);return <button type="button" onClick={onSelect} aria-pressed={selected} className={cn("grid min-w-0 gap-2 rounded-2xl border bg-paper p-4 text-start transition",selected?"border-ink bg-sand/40":"border-line hover:bg-sand/40")}><div className="flex min-w-0 items-start justify-between gap-3"><div className="min-w-0"><strong className="block break-words" dir="auto">#{order.orderNumber} · {customer}</strong><p className="mt-1 truncate text-xs text-muted" dir="auto">{order.branchName} · <span dir="ltr">{order.customerPhone||"—"}</span></p></div><Badge status={order.status} lang={lang}/></div><div className="flex min-w-0 flex-wrap justify-between gap-2 text-xs text-muted"><span><span dir="ltr">{order.itemCount}</span> {lang === "ar"?"عناصر":"items"} · <span dir="ltr">{money(order.total,order.currency,lang)}</span></span><span dir="ltr">{date(order.createdAt,lang)}</span></div></button>}

const OrderDetail=forwardRef<HTMLElement,{order:AdminOrder|null;lang:"ar"|"en";onBack:()=>Promise<void>;onStatus:(id:string,status:OrderStatus)=>Promise<void>}>(({order,lang,onBack,onStatus},ref)=>{
  const [secondary,setSecondary]=useState<OrderStatus>("confirmed"); const [confirmCancel,setConfirmCancel]=useState(false); if(!order)return <aside ref={ref} className="grid content-start gap-5 rounded-2xl border border-line bg-paper p-5"><Empty text={text(C.select,lang)}/></aside>;
  const phone=buildOrderContact(order.customerPhone); const whatsapp=buildOrderWhatsAppUrl(order,lang); const next=NEXT[order.status]; const secondaryStatuses=ORDER_STATUSES.filter(s=>s!==order.status&&s!==next&&s!=="cancelled"); const customer=order.customerName||text(C.customerFallback,lang);
  return <aside ref={ref} aria-label={lang === "ar"?`تفاصيل الطلب #${order.orderNumber}`:`Order #${order.orderNumber} details`} className="grid min-w-0 content-start gap-5 rounded-2xl border border-line bg-paper p-4 sm:p-5 lg:sticky lg:top-5 lg:h-fit">
    <div className="grid gap-3 border-b border-line pb-4"><div className="flex min-w-0 items-start justify-between gap-3"><div className="min-w-0"><p className="text-xs text-muted" dir="ltr">#{order.orderNumber}</p><h2 className="mt-1 break-words text-2xl font-semibold" dir="auto">{customer}</h2><p className="mt-1 text-sm text-muted" dir="auto">{order.branchName}</p></div><Badge status={order.status} lang={lang}/></div><div className="grid grid-cols-2 gap-2 text-xs text-muted sm:grid-cols-3"><Info label={text(C.branch,lang)} value={order.branchName}/><Info label={text(C.source,lang)} value={source(order.source,lang)}/><Info label={text(C.created,lang)} value={date(order.createdAt,lang)} ltr/></div></div>
    <section className="grid gap-3" aria-labelledby="order-contact-title"><div className="flex items-center gap-2"><UserRound className="size-4 text-accent"/><h3 id="order-contact-title" className="font-semibold">{text(C.contact,lang)}</h3></div><div className="rounded-2xl border border-line bg-sand/20 p-4"><p className="font-medium" dir="auto">{customer}</p>{phone?<p className="mt-1 text-sm text-muted" dir="ltr">{order.customerPhone}</p>:null}<div className="mt-3 flex flex-wrap gap-2">{phone&&whatsapp?<a className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-success px-4 text-sm font-medium text-white focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring" href={whatsapp} target="_blank" rel="noreferrer" aria-label={`${text(C.whatsapp,lang)} ${customer}`}><ExternalLink className="size-4"/>{text(C.whatsapp,lang)}</a>:null}{phone?<a className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl border border-line bg-paper px-4 text-sm font-medium text-ink focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring" href={phone.tel} aria-label={`${text(C.call,lang)} ${customer}`}><Phone className="size-4"/>{text(C.call,lang)}</a>:null}</div>{!phone?<p className="mt-2 text-sm text-muted">{text(C.noPhone,lang)}</p>:null}</div></section>
    <section className="grid gap-3" aria-labelledby="order-status-title"><div className="flex items-center justify-between gap-3"><div><p className="text-xs text-muted">{lang === "ar"?"الحالة الحالية":"Current status"}</p><h3 id="order-status-title" className="mt-1 font-semibold">{text(STATUS[order.status],lang)}</h3></div>{next?<span className="text-xs text-muted">{text(C.next,lang)}</span>:null}</div>{next?<Button className="min-h-12 w-full justify-between" onClick={()=>void onStatus(order.id,next)}>{text(NEXT_LABEL[next],lang)}<ArrowRight className="size-4 rtl:rotate-180"/></Button>:<div className="rounded-xl bg-sand/40 p-3 text-sm text-muted">{lang === "ar"?"لا توجد خطوة تشغيلية تالية مسجلة للحالة الحالية.":"There is no next operational step recorded for this status."}</div>}
      {secondaryStatuses.length?<div className="grid gap-2"><label className="text-xs font-medium text-muted" htmlFor="secondary-status">{text(C.change,lang)}</label><div className="flex min-w-0 flex-wrap gap-2"><select id="secondary-status" value={secondaryStatuses.includes(secondary)?secondary:secondaryStatuses[0]} onChange={e=>setSecondary(e.target.value as OrderStatus)} className="min-h-11 min-w-0 flex-1 rounded-xl border border-line bg-paper px-3 text-sm">{secondaryStatuses.map(s=><option key={s} value={s}>{text(STATUS[s],lang)}</option>)}</select><Button variant="outline" className="min-h-11" onClick={()=>void onStatus(order.id,secondary)}>{text(C.apply,lang)}</Button></div></div>:null}
      {order.status!=="cancelled"?<div className="pt-1">{confirmCancel?<div className="rounded-xl border border-danger/40 bg-danger/10 p-3"><div className="flex items-start gap-2"><ShieldAlert className="mt-0.5 size-4 shrink-0 text-danger"/><div><p className="font-medium">{text(C.confirmCancel,lang)}</p><p className="mt-1 text-xs leading-5 text-muted">{text(C.cancelBody,lang)}</p></div></div><div className="mt-3 flex flex-wrap gap-2"><Button variant="outline" onClick={()=>setConfirmCancel(false)}>{text(C.keep,lang)}</Button><Button className="bg-danger text-white hover:bg-danger/90" onClick={()=>{setConfirmCancel(false);void onStatus(order.id,"cancelled")}}>{text(C.confirm,lang)}</Button></div></div>:<Button variant="outline" className="min-h-11 text-danger" onClick={()=>setConfirmCancel(true)}><XCircle className="size-4"/>{text(C.cancel,lang)}</Button>}</div>:null}
    </section>
    <section className="grid gap-3" aria-labelledby="order-items-title"><div className="flex items-center justify-between gap-3"><h3 id="order-items-title" className="font-semibold">{text(C.items,lang)}</h3><span className="text-xs text-muted"><span dir="ltr">{order.itemCount}</span> {lang === "ar"?"عناصر":"items"}</span></div><div className="grid gap-2">{order.items.map(item=><OrderItem key={item.id} item={item} lang={lang} currency={order.currency}/>)}</div></section>
    <section className="grid gap-2 rounded-2xl border border-line bg-sand/20 p-4"><Info label={text(C.total,lang)} value={money(order.total,order.currency,lang)} strong ltr/>{order.subtotal!==order.total?<Info label={lang === "ar"?"الإجمالي الفرعي":"Subtotal"} value={money(order.subtotal,order.currency,lang)} ltr/>:null}</section>
    <section className="grid gap-2 rounded-2xl border border-line bg-paper p-4"><h3 className="font-semibold">{text(C.notes,lang)}</h3><p className="text-sm leading-6 text-muted" dir="auto">{order.notes||text(C.noNotes,lang)}</p></section>
    <Button variant="ghost" className="min-h-11 justify-start" onClick={()=>void onBack()}><ArrowLeft className="size-4 rtl:rotate-180"/>{text(C.back,lang)}</Button>
  </aside>;
});
function Info({label,value,strong=false,ltr=false}:{label:string;value:string;strong?:boolean;ltr?:boolean}){return <div className="min-w-0"><p className="text-[11px] text-muted">{label}</p><p className={cn("mt-1 break-words text-sm",strong&&"font-semibold")} dir={ltr?"ltr":"auto"}>{value}</p></div>}
function OrderItem({item,lang,currency}:{item:AdminOrder["items"][number];lang:"ar"|"en";currency:string}){const name=lang === "ar"?item.productNameAr||item.productNameEn:item.productNameEn||item.productNameAr;const selections=item.selectedOptions.filter(o=>o.type!=="note");const notes=item.selectedOptions.filter(o=>o.type==="note");return <div className="grid min-w-0 gap-2 rounded-xl border border-line bg-sand/30 px-3 py-3"><div className="grid grid-cols-[auto_minmax(0,1fr)_auto] items-start gap-3"><span className="rounded-lg bg-paper px-2 py-1 text-xs font-semibold tabular-nums" dir="ltr">×{item.quantity}</span><span className="min-w-0 break-words text-sm font-medium" dir="auto">{name||text(C.itemFallback,lang)}</span><span className="whitespace-nowrap text-sm font-medium" dir="ltr">{money(item.lineTotal,currency,lang)}</span></div>{selections.length?<p className="text-xs text-muted" dir="auto">{selections.map(o=>lang === "ar"?o.nameAr||o.nameEn:o.nameEn||o.nameAr).filter(Boolean).join(lang === "ar"?"، ":", ")}</p>:null}{notes.map(n=><p key={`${item.id}-${n.id}`} className="rounded-lg bg-paper/70 px-2 py-1 text-xs leading-5" dir="auto"><strong>{lang === "ar"?"ملاحظة الصنف:":"Item note:"}</strong> {lang === "ar"?n.nameAr||n.nameEn:n.nameEn||n.nameAr}</p>)}</div>}
