import type { PublicMenu } from "./types";

const DEMO_TENANT_ID = "demo-nafas-tenant";
const DEMO_BRANCH_ID = "demo-nafas-branch";

const image = (id: string) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=1200&q=82`;

/**
 * Stable, dependency-free demo content used by the marketing/theme previews.
 * It is intentionally local so public previews do not depend on production
 * tenant data being seeded or published.
 */
export const DEMO_MENU: PublicMenu = {
  tenant: {
    id: DEMO_TENANT_ID,
    ownerUserId: "demo-owner",
    slug: "nafas",
    nameAr: "نَفَس",
    nameEn: "Nafas",
    taglineAr: "قهوة مختصة ومخبوزات يومية",
    taglineEn: "Specialty coffee & daily pastry",
    logoUrl: "",
    coverUrl: image("photo-1495474472287-4d71bcdd2085"),
    instagramUrl: "",
    whatsapp: "",
    whatsappTemplate: "",
    primaryColor: "#171411",
    accentColor: "#a34b2f",
    themeKey: "essential",
    currency: "SAR",
    city: "Riyadh",
    country: "SA",
    isPublished: true,
    isActive: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  branch: {
    id: DEMO_BRANCH_ID,
    tenantId: DEMO_TENANT_ID,
    slug: "olaya",
    nameAr: "العليا",
    nameEn: "Al Olaya",
    addressAr: "العليا، الرياض",
    addressEn: "Al Olaya, Riyadh",
    mapsUrl: "",
    phone: "",
    isActive: true,
  },
  branches: [],
  hours: [],
  categories: [
    { id: "demo-coffee", tenantId: DEMO_TENANT_ID, sortOrder: 1, nameAr: "القهوة", nameEn: "Coffee", isActive: true },
    { id: "demo-pastry", tenantId: DEMO_TENANT_ID, sortOrder: 2, nameAr: "المخبوزات", nameEn: "Pastry", isActive: true },
    { id: "demo-cold", tenantId: DEMO_TENANT_ID, sortOrder: 3, nameAr: "بارد ومنعش", nameEn: "Cold & Fresh", isActive: true },
  ],
  products: [
    {
      id: "demo-espresso",
      tenantId: DEMO_TENANT_ID,
      categoryId: "demo-coffee",
      sortOrder: 1,
      nameAr: "إسبريسو مزدوج",
      nameEn: "Double Espresso",
      descriptionAr: "قهوة مركزة بنهاية شوكولاتية ناعمة.",
      descriptionEn: "A concentrated cup with a soft chocolate finish.",
      price: 16,
      currency: "SAR",
      imageUrl: image("photo-1514437215073-8b5b8f9b7a4a"),
      calories: 8,
      isAvailable: true,
      isFeatured: true,
      allergens: "",
      tags: ["coffee"],
      dietaryLabels: [],
    },
    {
      id: "demo-latte",
      tenantId: DEMO_TENANT_ID,
      categoryId: "demo-coffee",
      sortOrder: 2,
      nameAr: "لاتيه نَفَس",
      nameEn: "Nafas Latte",
      descriptionAr: "إسبريسو، حليب مبخر ولمسة فانيلا محمصة.",
      descriptionEn: "Espresso, steamed milk and toasted vanilla.",
      price: 22,
      currency: "SAR",
      imageUrl: image("photo-1572442388796-11668a67e53d"),
      calories: 140,
      isAvailable: true,
      isFeatured: true,
      allergens: "milk",
      tags: ["signature"],
      dietaryLabels: [],
    },
    {
      id: "demo-croissant",
      tenantId: DEMO_TENANT_ID,
      categoryId: "demo-pastry",
      sortOrder: 1,
      nameAr: "كرواسون زبدة",
      nameEn: "Butter Croissant",
      descriptionAr: "طبقات هشة مخبوزة صباحاً.",
      descriptionEn: "Flaky layers baked fresh each morning.",
      price: 18,
      currency: "SAR",
      imageUrl: image("photo-1555507036-ab1f4038808a"),
      calories: 260,
      isAvailable: true,
      isFeatured: false,
      allergens: "wheat,milk",
      tags: ["fresh"],
      dietaryLabels: [],
    },
    {
      id: "demo-cheesecake",
      tenantId: DEMO_TENANT_ID,
      categoryId: "demo-pastry",
      sortOrder: 2,
      nameAr: "تشيزكيك زعفران",
      nameEn: "Saffron Cheesecake",
      descriptionAr: "كريمي، خفيف، مع أثر زعفران عطري.",
      descriptionEn: "Creamy, light and finished with aromatic saffron.",
      price: 28,
      currency: "SAR",
      imageUrl: image("photo-1565958011703-44f9829ba187"),
      calories: 390,
      isAvailable: true,
      isFeatured: true,
      allergens: "milk,wheat",
      tags: ["dessert"],
      dietaryLabels: [],
    },
    {
      id: "demo-coldbrew",
      tenantId: DEMO_TENANT_ID,
      categoryId: "demo-cold",
      sortOrder: 1,
      nameAr: "كولد برو",
      nameEn: "Cold Brew",
      descriptionAr: "استخلاص بارد طويل بطعم نظيف ومنعش.",
      descriptionEn: "Long cold extraction with a clean, refreshing finish.",
      price: 20,
      currency: "SAR",
      imageUrl: image("photo-1517701604599-bb29b565090c"),
      calories: 12,
      isAvailable: true,
      isFeatured: false,
      allergens: "",
      tags: ["cold"],
      dietaryLabels: [],
    },
  ],
  productOptions: {},
};
