import type { PublicMenu } from "./types";

const DEMO_TENANT_ID = "demo-nafas-tenant";
const DEMO_BRANCH_ID = "demo-nafas-branch";
const image = (id: string) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=900&q=76`;

export const DEMO_MENU: PublicMenu = {
  tenant: {
    id: DEMO_TENANT_ID,
    slug: "nafas",
    nameAr: "نَفَس",
    nameEn: "Nafas",
    taglineAr: "قهوة مختصة ومخبوزات يومية",
    taglineEn: "Specialty coffee & daily pastry",
    logoUrl: "/demo/nafas-logo.svg",
    coverUrl: image("photo-1495474472287-4d71bcdd2085"),
    instagramUrl: "https://instagram.com/",
    whatsapp: "+966500000000",
    whatsappTemplate: "مرحباً، أود الاستفسار عن قائمة نَفَس.",
    primaryColor: "#344331",
    accentColor: "#b78a42",
    themeKey: "essential",
    currency: "SAR",
    city: "Riyadh",
    country: "SA",
    isPublished: true,
    isActive: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-09-19T00:00:00.000Z",
  },
  branch: {
    id: DEMO_BRANCH_ID,
    tenantId: DEMO_TENANT_ID,
    slug: "olaya",
    nameAr: "العليا",
    nameEn: "Al Olaya",
    addressAr: "العليا، الرياض",
    addressEn: "Al Olaya, Riyadh",
    mapsUrl: "https://maps.google.com/?q=Al+Olaya+Riyadh",
    phone: "+966500000000",
    isActive: true,
  },
  branches: [
    {
      id: DEMO_BRANCH_ID,
      tenantId: DEMO_TENANT_ID,
      slug: "olaya",
      nameAr: "العليا",
      nameEn: "Al Olaya",
      addressAr: "العليا، الرياض",
      addressEn: "Al Olaya, Riyadh",
      mapsUrl: "https://maps.google.com/?q=Al+Olaya+Riyadh",
      phone: "+966500000000",
      isActive: true,
    },
  ],
  hours: [
    { branchId: DEMO_BRANCH_ID, weekday: 0, opensAt: "07:00", closesAt: "23:30", isClosed: false },
    { branchId: DEMO_BRANCH_ID, weekday: 1, opensAt: "07:00", closesAt: "23:30", isClosed: false },
    { branchId: DEMO_BRANCH_ID, weekday: 2, opensAt: "07:00", closesAt: "23:30", isClosed: false },
    { branchId: DEMO_BRANCH_ID, weekday: 3, opensAt: "07:00", closesAt: "23:30", isClosed: false },
    { branchId: DEMO_BRANCH_ID, weekday: 4, opensAt: "07:00", closesAt: "00:30", isClosed: false },
    { branchId: DEMO_BRANCH_ID, weekday: 5, opensAt: "08:00", closesAt: "00:30", isClosed: false },
    { branchId: DEMO_BRANCH_ID, weekday: 6, opensAt: "08:00", closesAt: "23:30", isClosed: false },
  ],
  categories: [
    { id: "demo-coffee", tenantId: DEMO_TENANT_ID, sortOrder: 1, nameAr: "القهوة", nameEn: "Coffee", isActive: true },
    { id: "demo-signature", tenantId: DEMO_TENANT_ID, sortOrder: 2, nameAr: "التوقيع", nameEn: "Signature", isActive: true },
    { id: "demo-pastry", tenantId: DEMO_TENANT_ID, sortOrder: 3, nameAr: "المخبوزات والحلى", nameEn: "Pastry & Dessert", isActive: true },
    { id: "demo-cold", tenantId: DEMO_TENANT_ID, sortOrder: 4, nameAr: "بارد ومنعش", nameEn: "Cold & Fresh", isActive: true },
  ],
  products: [
    {
      id: "demo-espresso", tenantId: DEMO_TENANT_ID, categoryId: "demo-coffee", sortOrder: 1,
      nameAr: "إسبريسو مزدوج", nameEn: "Double Espresso", descriptionAr: "قهوة مركزة بنهاية شوكولاتية ناعمة.",
      descriptionEn: "A concentrated cup with a soft chocolate finish.", price: 16, currency: "SAR",
      imageUrl: image("photo-1514437215073-8b5b8f9b7a4a"), calories: 8, sodiumMg: 4, caffeineMg: 126, caffeineBasis: "per_cup", isAvailable: true, isFeatured: true,
      allergens: "", tags: ["coffee", "hot"], dietaryLabels: [],
    },
    {
      id: "demo-latte", tenantId: DEMO_TENANT_ID, categoryId: "demo-coffee", sortOrder: 2,
      nameAr: "لاتيه نَفَس", nameEn: "Nafas Latte", descriptionAr: "إسبريسو، حليب مبخر ولمسة فانيلا محمصة.",
      descriptionEn: "Espresso, steamed milk and toasted vanilla.", price: 22, currency: "SAR",
      imageUrl: image("photo-1572442388796-11668a67e53d"), calories: 140, sodiumMg: 95, caffeineMg: 96, caffeineBasis: "per_cup", isAvailable: true, isFeatured: true,
      allergens: "milk", tags: ["signature", "coffee"], dietaryLabels: [],
    },
    {
      id: "demo-spanish", tenantId: DEMO_TENANT_ID, categoryId: "demo-signature", sortOrder: 1,
      nameAr: "سبانش لاتيه بالزعفران", nameEn: "Saffron Spanish Latte", descriptionAr: "لاتيه بارد، حليب مكثف ولمسة زعفران عطرية.",
      descriptionEn: "Iced latte with condensed milk and aromatic saffron.", price: 26, currency: "SAR",
      imageUrl: image("photo-1517701604599-bb29b565090c"), calories: 210, sodiumMg: 110, caffeineMg: 90, caffeineBasis: "per_cup", isAvailable: true, isFeatured: true,
      allergens: "milk", tags: ["signature", "cold"], dietaryLabels: [],
    },
    {
      id: "demo-croissant", tenantId: DEMO_TENANT_ID, categoryId: "demo-pastry", sortOrder: 1,
      nameAr: "كرواسون زبدة", nameEn: "Butter Croissant", descriptionAr: "طبقات هشة مخبوزة صباحاً.",
      descriptionEn: "Flaky layers baked fresh each morning.", price: 18, currency: "SAR",
      imageUrl: image("photo-1555507036-ab1f4038808a"), calories: 260, sodiumMg: 410, isAvailable: true, isFeatured: false,
      allergens: "wheat,milk", tags: ["fresh"], dietaryLabels: [],
    },
    {
      id: "demo-cheesecake", tenantId: DEMO_TENANT_ID, categoryId: "demo-pastry", sortOrder: 2,
      nameAr: "تشيزكيك زعفران", nameEn: "Saffron Cheesecake", descriptionAr: "كريمي، خفيف، مع أثر زعفران عطري.",
      descriptionEn: "Creamy, light and finished with aromatic saffron.", price: 28, currency: "SAR",
      imageUrl: image("photo-1565958011703-44f9829ba187"), calories: 390, sodiumMg: 260, isAvailable: true, isFeatured: true,
      allergens: "milk,wheat", tags: ["dessert"], dietaryLabels: [],
    },
    {
      id: "demo-cinnamon", tenantId: DEMO_TENANT_ID, categoryId: "demo-pastry", sortOrder: 3,
      nameAr: "رول قرفة", nameEn: "Cinnamon Roll", descriptionAr: "عجين طري، قرفة دافئة وتغطية كريمية خفيفة.",
      descriptionEn: "Soft pastry, warm cinnamon and a light cream glaze.", price: 19, currency: "SAR",
      imageUrl: image("photo-1509440159596-0249088772ff"), calories: 320, sodiumMg: 290, isAvailable: true, isFeatured: false,
      allergens: "wheat,milk", tags: ["fresh"], dietaryLabels: [],
    },
    {
      id: "demo-coldbrew", tenantId: DEMO_TENANT_ID, categoryId: "demo-cold", sortOrder: 1,
      nameAr: "كولد برو", nameEn: "Cold Brew", descriptionAr: "استخلاص بارد طويل بطعم نظيف ومنعش.",
      descriptionEn: "Long cold extraction with a clean, refreshing finish.", price: 20, currency: "SAR",
      imageUrl: image("photo-1517701604599-bb29b565090c"), calories: 12, sodiumMg: 8, caffeineMg: 155, caffeineBasis: "per_cup", isAvailable: true, isFeatured: false,
      allergens: "", tags: ["cold"], dietaryLabels: [],
    },
    {
      id: "demo-matcha", tenantId: DEMO_TENANT_ID, categoryId: "demo-cold", sortOrder: 2,
      nameAr: "ماتشا لاتيه", nameEn: "Matcha Latte", descriptionAr: "ماتشا ناعمة مع حليب بارد وتوازن نباتي لطيف.",
      descriptionEn: "Smooth matcha with chilled milk and a gentle vegetal finish.", price: 24, currency: "SAR",
      imageUrl: image("photo-1515823064-d6e0c04616a7"), calories: 130, sodiumMg: 80, caffeineMg: 70, caffeineBasis: "per_cup", isAvailable: true, isFeatured: true,
      allergens: "milk", tags: ["cold"], dietaryLabels: [],
    },
  ],
  productOptions: {
    "demo-latte": {
      variants: [
        { id: "demo-latte-small", tenantId: DEMO_TENANT_ID, productId: "demo-latte", nameAr: "صغير", nameEn: "Small", price: 22, sortOrder: 1, isAvailable: true },
        { id: "demo-latte-large", tenantId: DEMO_TENANT_ID, productId: "demo-latte", nameAr: "كبير", nameEn: "Large", price: 26, sortOrder: 2, isAvailable: true },
      ],
      groups: [
        { id: "demo-latte-milk", tenantId: DEMO_TENANT_ID, nameAr: "نوع الحليب", nameEn: "Milk choice", minSelect: 1, maxSelect: 1, sortOrder: 1, isRequired: true, isActive: true },
      ],
      options: [
        { id: "demo-latte-oat", tenantId: DEMO_TENANT_ID, groupId: "demo-latte-milk", nameAr: "حليب الشوفان", nameEn: "Oat milk", priceDelta: 4, sortOrder: 1, isAvailable: true },
        { id: "demo-latte-almond", tenantId: DEMO_TENANT_ID, groupId: "demo-latte-milk", nameAr: "حليب اللوز", nameEn: "Almond milk", priceDelta: 4, sortOrder: 2, isAvailable: true },
      ],
    },
  },
};
